fix: build wal-g

diff --git a/wal-g/Dockerfile b/wal-g/Dockerfile
--- a/wal-g/Dockerfile
+++ b/wal-g/Dockerfile
@@ -11,6 +11,8 @@ WORKDIR /go/src/
 
 ARG APPVERSION
 RUN git clone --single-branch --depth 2 --branch ${APPVERSION} https://github.com/wal-g/wal-g.git .
+# Fix: fail if commit has two tags
+RUN git tag -d v3.0.6 ||:
 
 ENV USE_LIBSODIUM=1 USE_BROTLI=1
 ENV GOBIN=/usr/local/bin
